[package]
description = "Constant ANSI codes for easy styling and formatting helpers"
name = "ts-ansi"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true
