[package]
name = "ts-ansi"
version = "0.1.0"

authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
strip-ansi-escapes = "0.2"

[lints]
workspace = true
