[package]
name = "ts-cli"
version = "0.1.0"

authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ts-ansi = { version = "0.1", path = "../ts-ansi" }

[lints]
workspace = true
