[package]
description = "Helpers for creating my CLIs"
name = "ts-terminal"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ts-ansi = { version = "0.1", path = "../ts-ansi" }

[lints]
workspace = true
