[package]
description = "Helpers for input/output related work"
name = "ts-io"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ts-path = { version = "0.1", path = "../ts-path" }

[lints]
workspace = true
