[package]
description = "Helpers for working with paths"
name = "ts-path"
version = "0.2.1"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
