[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
name = "ts-json"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

jsonschema = { version = "0.30", default-features = false }
ts-ansi = { version = "0.1", path = "../ts-ansi" }
ts-error = { version = "0.1", path = "../ts-error" }

[lints]
workspace = true
